<a href="https://colab.research.google.com/github/mdarshlankhan743/Designuiux/blob/main/DPricePred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("Diamond Price Prediction.csv")
df.sample(10)

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
9288,1.06,Ideal,F,SI2,60.7,57.0,4568,6.57,6.61,4.00
32727,0.31,Ideal,F,VS2,61.3,57.0,802,4.34,4.30,2.65
2450,0.91,Very Good,G,SI2,60.3,59.0,3189,6.23,6.28,3.77
20173,1.02,Very Good,F,VVS2,59.4,59.0,8627,6.58,6.69,3.94
617,0.71,Premium,F,VS1,59.2,58.0,2839,5.87,5.82,3.46
12700,0.26,Good,E,VVS2,63.1,59.0,599,4.04,4.08,2.56
4023,0.96,Good,G,SI1,56.6,63.0,3522,6.52,6.39,3.67
38745,0.35,Ideal,G,IF,61.8,55.0,1044,4.54,4.56,2.81
11976,1.20,Premium,I,SI2,62.7,58.0,5141,6.82,6.76,4.26
3791,0.73,Ideal,H,VVS2,61.6,56.0,3463,5.80,5.82,3.57

In [5]:
df.head()

,Carat(Weight of Daimond),Cut(Quality),Color,Clarity,Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Carat(Weight of Daimond)  53940 non-null  float64
 1   Cut(Quality)              53940 non-null  object
 2   Color                     53940 non-null  object
 3   Clarity                   53940 non-null  object
 4   Depth                     53940 non-null  float64
 5   Table                     53940 non-null  float64
 6   Price(in US dollars)      53940 non-null  int64
 7   X(length)                 53940 non-null  float64
 8   Y(width)                  53940 non-null  float64
 9   Z(Depth)                  53940 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB

In [7]:
df.shape

(53940, 10)

In [8]:
len(df)

53940

In [9]:
df.shape[1]

10

In [11]:
df.columns

Index(['Carat(Weight of Daimond)', 'Cut(Quality)', 'Color', 'Clarity', 'Depth',
       'Table', 'Price(in US dollars)', 'X(length)', 'Y(width)', 'Z(Depth)'],
      dtype='object')

In [12]:
len(df.columns)-1

9

In [14]:
df.columns[-1]

'Z(Depth)'

In [15]:
df.iloc[:,6:7]

       Price(in US dollars)
0                       326
1                       326
2                       327
3                       334
4                       335
...                     ...
53935                  2757
53936                  2757
53937                  2757
53938                  2757
53939                  2757

[53940 rows x 1 columns]

In [16]:
df.dtypes

Carat(Weight of Daimond)    float64
Cut(Quality)                 object
Color                        object
Clarity                      object
Depth                       float64
Table                       float64
Price(in US dollars)          int64
X(length)                   float64
Y(width)                    float64
Z(Depth)                    float64
dtype: object

In [17]:
df.isnull().sum()

Carat(Weight of Daimond)    0
Cut(Quality)                0
Color                       0
Clarity                     0
Depth                       0
Table                       0
Price(in US dollars)        0
X(length)                   0
Y(width)                    0
Z(Depth)                    0
dtype: int64

In [18]:
df.describe()

,Carat(Weight of Daimond),Depth,Table,Price(in US dollars),X(length),Y(width),Z(Depth)
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000